FROM node:18-alpine as build
WORKDIR /usr/src/app
COPY frontend/package*.json ./
RUN npm ci --silent
COPY frontend/ .
RUN npm run build -- --output-path=dist --configuration=production

FROM nginx:stable-alpine
COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
